### ISSUE TITLE
Array in Array in Array...

### ISSUE THREAD

**Issue by ismaelmoran** [adammark/Markup.js#37]
Hello, Mark.

I have a problem with my simple JSON. How can I attack to this?

"items" : [
                    [
                      "A"
                      ,"B"
                      ,[
                           ["C-1", "C-2", "C-3"]
                           ,[ ....... ]
                      ]
                    ]
                   ,[ ....... ]
             ]

It seems I can only iterate whit one array.

{{items}}
    {{0}}, {{1}}
    {{2}}
      ?????
    {{/2}}
{{/items}}

Thanck you!

**Comment by adammark** [comment]
Hi there,

Sorry for the delayed response. First, I think your data structure is strange—generally, the values in an array should all have the same type. Also, can you simplify the structure at all? It's very nested and hard to read. That said, you can try something like this:

``` javascript
var context = {
    items: ["a", "b", ["c1", "c2"]]
};
var template = "{{items.0/}} {{items.1/}} {{items.2}} *{{.}}* {{/items.2}}";
var markup = Mark.up(template, context);
markup === "a b  *c1*  *c2* "; // true
```

This also works, although it's ridiculous:

``` javascript
Mark.pipes.isArray = function (val) {
   return val instanceof Array;
};

var context = {
    items: ["a", "b", ["c1", "c2"]]
};
var template = "{{items}}{{if .|isArray}}{{.}} *{{.}}* {{/.}}{{else}} -{{./}}- {{/if}}{{/items}}";
var markup = Mark.up(template, context);
markup === " -a-  -b-  *c1*  *c2* "; // true
```

As I said, the best thing would be to simplify and normalize your data structure. Hope this helps.

Adam
