### ISSUE TITLE
Access property from parent when inside loop

### ISSUE THREAD

**Issue by kouts** [adammark/Markup.js#38]
Hi! Is it possible to access a property of the parent object when we loop?
For example:
```
var context = {
    name: "John Doe",
    brothers: ["Jack", "Joe", "Jim"]
};

var template = "<ul>{{brothers}}<li>{{.}}</li>{{/brothers}}</ul>";
```
How do I access "name" (John Doe) inside the "{{brothers}}" loop?

**Comment by adammark** [comment]
Hi, thanks for the question. Sorry to say it's not possible. You should simply modify the data structure before handing it off to the template engine.

Adam
