### ISSUE TITLE
| sanitize not working?

### ISSUE THREAD

**Issue by mdix** [adammark/Markup.js#41]
I just tried to get the sanitize filter to work, but it's not working as expected.
1. I'm including `markup.js`
2. I'm including `extras/strings.js`
3. I'm using the `| sanitize` pipe in my placeholder

Please check the codepen. In the JS tab I first included markup.js, then extras/strings.js and finally used sanitize (at the end of the tab, sorry for the unconvenient handling, did not find markup.js on cdnjs):

http://codepen.io/anon/pen/yNyQLN

The link in the output should not be a link after `| sanitize`.

Best
Marc

**Comment by ajinabraham** [comment]
https://github.com/adammark/Markup.js/pull/59

**Comment by adammark** [comment]
Thanks for the note. Should be fixed by PR #59.
