### ISSUE TITLE
If statement with multiple conditions and else?

### ISSUE THREAD

**Issue by mdix** [adammark/Markup.js#44]
Hi,

I've read that IF-Statements can be nested. That's fine, so we can have multiple conditions. But what if we want to use else?

Example:

```
if (valueA && valueB) {
    doSomething();
}
```

could be expressed as:
```
{{if valueA}}
{{if valueB}}
doSomething
{{/if}}
{{/if}}
```

but:
```
if (valueA && valueB) {
    doSomething();
} else {
   doSomethingDifferent();
}
```

can not be expressed as:
```
{{if valueA}}
{{if valueB}}
doSomething
{{/if}}
{{else}}
doSomethingDifferent
{{/if}}
```

so two scenarios come to my mind where one is wrong:
* OK: valueA is false, we'll directly go to the else branch
* NOT OK: valueA is true, but valueB is false, we'll never go to the else branch

We'd need something that contains duplication and is as complex as:
```
{{if valueA}}
{{if valueB}}
doSomething
{{else}}
doSomethingDifferent
{{/if}}
{{else}}
doSomethingDifferent
{{/if}}
```

Is there any other way? I tried to set a variable to true with set, but this didn't work for me:

```
{{if valueA}}
{{if valueB}}
    {{true|set>bothValuesAreTrue}}
{{/if}}
{{/if}}
```

Seems you can't use set without a variable.

Thanks for your help and best
Marc

**Comment by adammark** [comment]
Thanks for the feedback. I don't think I anticipated this scenario. But may I suggest you're putting a bit too much logic in the template? Can you set the variable in the model instead, such that your template is easier to read and write?

```
{{if isAandB}}
   ...
{{else}}
  ...
{{//if}}
```
