### ISSUE TITLE
Consider changing > character in pipes

### ISSUE THREAD

**Issue by izolate** [adammark/Markup.js#50]
I'm having trouble with the `>` character in the following pipe:

```
<h1>{{title|blank>N/A}}</h1>
```
This conflicts with the [`Element.innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) method due to it returning `<` as `&gt;`
```
h1.innerHTML // <h1>{{title|blank&gt;N/A}}</h1>
```

Please consider using an alternate character or different syntax. Cheers.

**Comment by adammark** [comment]
Thanks for the feedback. See https://github.com/adammark/Markup.js#changing-the-argument-delimiter

Adam

**Comment by izolate** [comment]
I need to learn how to read. Thanks for this.
