### ISSUE TITLE
I love this library.

### ISSUE THREAD

**Issue by marcog83** [adammark/Markup.js#52]
Please don't give up with this library. I use it a lot in real world projects and I'd like to see how far it can go. Thanks a lot. If you decided to stop maintaining because of some alternatives, please, let me know what they are, 'cause I think
 this is a really well done project

Marco

**Comment by harrisonhjones** [comment]
I like markup.js as well. I didn't even consider that it might be "dead". 

I know some are using [Handlebars](http://handlebarsjs.com/).

**Comment by adammark** [comment]
Thanks for the nice feedback! I still maintain it (lightly) but don't intend to add any more functionality. I've actually switched to React—but Markup.js is still good for string templating.

Regards,
Adam
