### ISSUE TITLE
How to get a variable replaced when the value comes from the context?

### ISSUE THREAD

**Issue by CycoPH** [adammark/Markup.js#53]
I have a list of items that need to get server IPs replaced with actual context data.
Context data is something like:
{
	"ABC_ip": "hello",
	"CDE_ip": "fun",
	"ext_servers": [
		{"name":"a", "address":"{{ABC_ip}}", "port":9100},
		{"name":"b", "address":"{{CDE_ip}}", "port":9120},
		{"name":"c", "address":"{{CDE_ip}}", "port":9040},
		{"name":"d", "address":"{{ABC_ip}}", "port":9150}
	]
}

The template I'm trying to use is:
{
	"hellos":[
		{{ext_servers}}
		{"name":"{{name}}", "address": "tcp://{{address}}:{{port}}"} {{if #|last}} {{else}} , {{/if}} 
		{{/ext_servers}}
	]
}

This will produce a list:
"hellos":[{"name":"a", "address": "tcp://{{ABC_ip}}:9100"}  , ....]

How do I get that {{ABC_ip}} replaced with the value at the top of the context?

**Comment by adammark** [comment]
It looks like you expect for the context data itself to contain tokenized strings. Rather, the context data should contain only data, and the template should do the work of transforming it. So your data should look like:

```
{
  "ext_servers": [
    {"name":"a", "address":"hello", "port":9100},
    {"name":"b", "address":"fun", "port":9120},
    {"name":"c", "address":"fun", "port":9040},
    {"name":"d", "address":"hello", "port":9150}
  ]
}
```

It's both easier to read and easier to work with. Hope this helps!

Adam

**Comment by CycoPH** [comment]
That is one solution, I used that before but the address part gets taken from a long list that is dynamic, so having the same address in multiple locations becomes a bit of a problem.  My solution was to add a second pass to my deployment tool.  So the first pass goes and replaces some variables and the second pass does the rest.
