### ISSUE TITLE
testing for existence of boolean property

### ISSUE THREAD

**Issue by davidh71** [adammark/Markup.js#54]
Hi, I just started using this library - i'm really liking it compared to the other template libs.
How can you test for the **existence **of a property that is a boolean. I must not be using the correct pipes because it thinks the boolean value of false means it doesn't exist.

var context = { name:"bob", thing:false };
var template = "{{if thing|notempty}} the attribute thing exists and has value of {{thing}} {{/if}}";
Mark.up(template, context);

i would expect this to return:
_"the attribute thing exists and has value of false"_
but it returns:
_""_

is there anything equivalent to hasOwnProperty ?
Many Thanks

**Comment by adammark** [comment]
Hi. Perhaps the documentation is unclear, but the "notempty" pipe considers false to be empty.

``` javascript
notempty: function (obj) {
    return obj && (obj + "").trim().length ? obj : false;
},
```

If you just want to check for the presence of a property, perhaps you could write your own pipe, e.g.

``` javascript
Mark.pipes.hasProperty = function (obj) {
  return obj !== undefined;
};
```

Let me know if this helps.

**Comment by davidh71** [comment]
That's perfect.  It would be a great addition to the default pipes.  Thanks for the response!
