### ISSUE TITLE
test for equals of another context variable

### ISSUE THREAD

**Issue by davidh71** [adammark/Markup.js#56]
Hi,
Any suggestion on how I would test for the value in another context variable?

illustrative example:
context = {"things":[{"name":"a"},{"name":"b"},{"name":"c"}],"answer":"a"}

{{things}}
{{if name|equals>answer}} do this... {{/if}}
{{/things}}

Thanks

**Comment by adammark** [comment]
I would transform the data before sending it to the template. This will make your presentation logic easier to read and write. For example:

```
var context = {
  things: things.map(function (thing) {
    return { name: thing.name, correct: thing.name === answer }
  });
};
```

```
{{things}}
  {{if thing.correct}} ... {{/if}}
{{/things}}
```

Make sense?

**Comment by davidh71** [comment]
yup, thanks.
